# Generated by Django 3.0.2 on 2020-01-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('episode_name', models.CharField(max_length=128)),
                ('filesize_kb', models.IntegerField(blank=True, null=True)),
                ('origin_url', models.CharField(max_length=256)),
                ('s3_url', models.CharField(max_length=256)),
                ('processing_status', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'episode',
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('rss_url', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'podcast',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'subscription',
            },
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_transcription_download_location', models.CharField(blank=True, max_length=4096, null=True)),
                ('raw_transcription', models.TextField(blank=True, null=True)),
                ('formatted_transcription', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transcription',
            },
        ),
    ]
