# Generated by Django 3.0.2 on 2020-01-26 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='podcast',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='transcription',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='episode',
            name='podcast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ui.Podcast'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='podcast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ui.Podcast'),
        ),
        migrations.AddField(
            model_name='transcription',
            name='episode',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ui.Episode'),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('podcast', 'episode_name')},
        ),
    ]
